In [1]:
# NUMPY --> NUMERICAL PYTHON

In [2]:
# numpy arrays

list_a = [1,2,3]

In [3]:
type(list_a)

list

In [4]:
import numpy as np

In [5]:
np_array_a = np.array(list_a)

In [6]:
type(np_array_a)

numpy.ndarray

In [8]:
# !pip install numpy

In [9]:
np_matrix = np.array([
    [1,2,3],
    [5,7,8],
    [8,3,6]
])

In [10]:
type(np_matrix)

numpy.ndarray

In [12]:
# arange function 
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [15]:
# zeros and ones

zero = np.zeros(3)
one = np.ones(5)

In [16]:
print(zero)

[0. 0. 0.]


In [17]:
print(one)

[1. 1. 1. 1. 1.]


In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.dtype

numpy.dtype

In [23]:
# int32

In [25]:
# identity matrix
identity = np.eye(3)

In [28]:
identity.shape

(3, 3)

In [29]:
one.shape

(5,)

In [34]:
# random

np.random.rand(5)

# range --> 0 to 1

array([0.84916224, 0.01032336, 0.57180933, 0.09872857, 0.94783599])

In [53]:
matrix_02 = np.random.rand(2,5)

In [39]:
matrix_02.shape

(2, 5)

In [54]:
matrix_02

array([[0.05085639, 0.05358806, 0.92011924, 0.24528565, 0.86625898],
       [0.51621439, 0.96487867, 0.38654236, 0.77505728, 0.37005433]])

In [43]:
matrix_02 = matrix_02.reshape(5,2)

In [44]:
matrix_02

array([[0.56000259, 0.27405203],
       [0.62932324, 0.17116062],
       [0.00430462, 0.71835249],
       [0.25439989, 0.84373424],
       [0.92488831, 0.48477958]])

In [46]:
# matrix_02 = matrix_02.reshape(4,2) --> this will give error

In [47]:
matrix_02.min()

0.00430462119385755

In [50]:
np.log(matrix_02)

array([[-0.57981387, -1.29443731],
       [-0.46311026, -1.76515285],
       [-5.44806614, -0.3307949 ],
       [-1.36884788, -0.16991772],
       [-0.07808229, -0.72406097]])

In [51]:
matrix_02**2

array([[3.13602900e-01, 7.51045133e-02],
       [3.96047743e-01, 2.92959585e-02],
       [1.85297636e-05, 5.16030300e-01],
       [6.47193040e-02, 7.11887459e-01],
       [8.55418392e-01, 2.35011238e-01]])

In [58]:
matrix_02 - matrix_02

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])